### ISSUE TITLE
It's seems the Reload PAC doesn't work on FF 69.0

### ISSUE THREAD

**Issue by dzdhome** [timendum/proxy-reload#5]
Hi Timendum

It's seems the Reload PAC doesn't work on FF 69.0. Could you update it? 

Thank you very much.

**Comment by timendum** [comment]
Hi,  
I think the problem is the _private windows access_, the extension does not work without access to private windows, because of a Firefox limitation.

Can you check [these instructions](https://support.mozilla.org/kb/extensions-private-browsing#w_enabling-or-disabling-extensions-in-private-windows) and see if this solve the issue?

I've also released a new version with a warning about this.

**Comment by dzdhome** [comment]
Hi Timendum

It's true. After I reset the private windows access, that's work. Thank you very much!
